name: Close Issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Auto Closer
      uses: lowply/auto-closer@0.0.3
      env: 
        AC_LABEL: kind/question
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
