name: Close Issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Auto Closer
      uses: bdougie/close-issues-based-on-label@master
      env:
        LABEL: kind/question
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
